#!/bin/bash

# This script is a wrapper for some functionality on Samsung Ativ Book 9 Plus
# laptops, with the intention that these functions be mapped to the fn-keys
# using a display manager (in my case, dwm).  It is provided as-is; use at your
# own risk.
#
# For reference, the function key x11 hex reference will be given with the
# corresponding function.

# Control the brightness of the screen backlight
#
# This queries for the backlight brightness and max brightness in /sys/, and
# expects a parameter from the command line, which is how much you want to
# brighten the screen (negative values darken the backlight).
#
# Brightness up key hex reference: 0x1008ff02
# Brightness down key hex reference: 0x1008ff03
#
# NB script needs root/sudo elevation for this to work
brightness () {
  brt_target='/sys/class/backlight/intel_backlight/brightness'
  max_target='/sys/class/backlight/intel_backlight/max_brightness'

  brightness=$(<$brt_target)
  new_brightness=$(($brightness+$1))
  max_brightness=$(<$max_target)
  
  if [ $verbose -eq 1 ]; then
    echo "current brightness: $brightness, incrementing by $1"
  fi

  if [ $new_brightness -gt $max_brightness ]; then
    echo $max_brightness > $brt_target
  elif [ $new_brightness -lt 0 ]; then
    echo 1 > $brt_target
  else
    echo $new_brightness > $brt_target
  fi
}

OPTIND=1	# Reset in case getopts has been invoked previously
verbose=0	# Randy!

while getopts "h?vb:" opt; do
  case "$opt" in
  h|\?)
    show_help
    exit 0
    ;;
  v) verbose=1 ;;
  b) brightness $OPTARG ;;
  esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

# EOF
